### PR TITLE
script to generate meson.build

### PR DESCRIPTION
**Pull request by Xed89**

### CODE REVIEW

**Comment by Xed89** [comment]
the meson.build file is already outdated because launcher.vala was added

**Comment by Xed89** [comment]
I could have .gitignore'd it but this, but this way who uses vscode needs to generate it before being ready to go.

**Comment by dbartolini** [comment]
Can you rebase to master and update meson.build?

I could try integrate .meson generation into GENie after this, to avoid the need for `create-meson-build.lua` altogether.

**Comment by Xed89** [comment]
The generation script is already correct, if you're going to integrate it into GENie isn't a merge sufficient?

**Comment by dbartolini** [comment]
The script is okay, but you mentioned meson.build is outdated so I thought it would be nice to have it up-to-date with master. It's fine though, I can merge this and do update meson.build myself later.

**Comment by dbartolini** [comment]
Merged manually: 96abb8626c1b6abd7e7fac78b6a44d4badc64f1e.

**Pull request closed without merging**
